lang: 'ru.yml'

events:
  demo-queue-1:
    name: "<!i>Demo queue 1"
    description:
      - "<!i>Demo queue 1 description"
    item: STONE
    capacity: 2
    demo-event-1-1:
      name: "<!i>Demo 1-1"
      description:
        - "<!i>Demo 1-1 description"
      type: "Demo"
      chance: 50
      duration: 60
      cooldown: 60
    demo-event-1-2:
      name: "<!i>Demo 1-2"
      description:
        - "<!i>Demo 1-2 description"
      type: "Demo"
      chance: 50
      duration: 60
      cooldown: 60
  demo-queue-2:
    name: "<!i>Demo queue 2"
    description:
      - "<!i>Demo queue 2 description"
    item: GRASS_BLOCK
    capacity: 2
    demo-event-2-1:
      name: "<!i>Demo 2-1"
      description:
        - "<!i>Demo 2-1 description"
      type: "Demo"
      chance: 50
      duration: 120
      cooldown: 120
    demo-event-2-2:
      name: "<!i>Demo 2-2"
      description:
        - "<!i>Demo 2-2 description"
      type: "Demo"
      chance: 50
      duration: 120
      cooldown: 120
